### ISSUE TITLE
Create Gradle main build pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1213]

**Comment by jadecarino** [comment]
@techcobweb @hobbit1983 @Jimbo4794 

Same as with Wrapping, would be fab to get another set of eyes on this before we close the work item for the Gradle main build.

- The YAML for this pipeline can be found in the automation repo in pipelines/pipelines/gradle
- The Tekton build is here https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-gradle-main-gvbhv?pipelineTask=clone-automation&step=clone
- The maven artifact repo is here https://development.galasa.dev/main/maven/gradle/
- The docker image is here https://harbor.galasa.dev/harbor/projects/3/repositories/galasa-gradle/artifacts-tab

Thanks!

**Comment by techcobweb** [comment]
Haven't had time to look very deeply... 
Some things which jumped out...

- Docker files running as root ?
- Docker files FROM images don't specify the version/tag... so two builds of the same code could pick up different dependencies. Builds should be reproduceable by not relying on latest Alpine image for example...

We should eventually be scanning the images for security issues and the like, so should find out if things are out-of-date ?

**Comment by techcobweb** [comment]
Pipeline and Task specs could do with some 
`description:` tags to document what the parameters are expected to hold ?

Using something like this in the pipelinerun spec and pod specs will stop argocd pruning things and cleaning them up:
```
      metadata:
        generateName: $(tt.params.pipelineName)-
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
```

If we can do that, then we can turn the prune option on in argocd... which would be good.

**Comment by techcobweb** [comment]
Git cloning depth always being set to "99999999" will take far longer than 'leaner' commits.
We probs only need smaller depth of 50, so we can see the last 50 commits in the checked-out code ? - Again, it's an optimisation which can be done later.

Similarly, there is no need to clone every branch in the repos... are we doing that ?

**Comment by techcobweb** [comment]
Seems that we always use the head of the automation repo.
Would make builds more reproduceable if the automation stuff was built separately and versioned, and pulled-down as a versioned jar or zip ? 
Think this is a wider question than this one PR...

**Comment by techcobweb** [comment]
This is a problem maybe... maybe I don't know what the events look like...
```
  - name: clone-gradle
    taskRef: 
      name: git-clone
    runAfter:
      - clone-automation
    params:
    - name: url
      value: https://github.com/galasa-dev/gradle
    - name: revision
      value: main
    - name: refspec
      value: refs/heads/main:refs/heads/main
```

We should be getting the revision and refspec from a parameter on the webhook...
Not hard-coding it to build the head...

Two merges to main would potentially build the same branch code level... despite the web hook events passing a more specific level of the repo we should be building ?

We can use bindings and templates to fish out this info from the webhook events like we do for PR builds...
