### ISSUE TITLE
Optimise build pipelines: add argoCD options to stop pruning of resources

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1223]
We should add some argocd options to the specs for certain resources used in the Pipelines so that argocd doesn't prune them as default. Pruning can then be turned on in argocd itself.

```
metadata:
        generateName: $(tt.params.pipelineName)-
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
```
