### ISSUE TITLE
Rest API: Resources endpoint bad property update failure message

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1697]
`galasactl resources update -f property.yaml --log -`
Where property.log contains this content:
```
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
    namespace: simbank
    name: my.new.property
data:
    value: SIMBANK
```

I can see that the server is replying with this (from the cli log):
```
2023/12/15 10:13:13 sendResourcesRequestToServer Failed - HTTP response - status code:400 payload:[
  "{\"error_code\":5017,\"error_message\":\"GAL5017E: Error occured when trying to access property \u0027my.new.property\u0027. The property name provided is invalid.\"}"
```

- Http status is good. 400 Bad request.
- There is nothing wrong with the name of the property. Or should be nothing wrong. Why are we getting unicode characters returned in the string ? Something is uuencoding the json when it should be a byte array payload. ?
- The actual problem I was expecting should have said something like "cannot update property my.new.property, because the property does not exist." or similar.
