### ISSUE TITLE
As a Galasa Ecosystem administrator I need an easier way to manage CPS properties applied to an ecosystem via a file

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1904]
## Story
As a Galasa Ecosystem administrator I need an easier way to manage CPS properties applied to an ecosystem via a file

## Background
I am currently looking at changing to a config as code way of managing CPS properties for a Galasa ecosystem. I am building up a YAML file that can be passed to the following command:

```
galasactl resources apply --file cps_properties.yaml
```

However, I am finding that due to the amount of extra surrounding information that needs to be stored per property, this file is ended up being very large and hard to manage:

```
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
    namespace: propertynamespace
    name: property.name
data:
    value: propertyvalue
---
```

I think it would make more sense to have the option to supply a more compact CPS properties yaml file, perhaps using a more traditional YAML approach to the way variables are organised e.g. separating by namespace like this:

```
framework:
    property.name.1: value
    property.name.2: value2
another_namespace:
    property.name.3: value
```
