### ISSUE TITLE
--override flags dont work when passing to a remote test

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1916]
## Describe the bug
Set off test with portfolio item like this:
```
    - bundle: dev.galasa.inttests
      class: dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu
      stream: inttests
      obr: ""
      overrides:
        framework.produce.events: "true"
      gherkin: ""
```

But run log said:
```
02/07/2024 09:41:18.777 DEBUG d.g.f.TestRunner - CPS property framework.produce.events was found and is set to: false
```

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.
