### ISSUE TITLE
Galasa Resources Apply fails if properties are given an empty value, even though ETCD accepts properties that are empty

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#2115]
## Describe the bug
Galasa Resources Apply fails if properties are given an empty value, even though ETCD accepts properties that are empty. The capabilities of Galasactl and the backend Etcd should match.

## Steps to reproduce
1. Create this file as "resources.yaml"

```
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
    namespace: demo
    name: empty.prop.demo
data:
    value: ""
```

2. Run this command:
```
galasactl resources apply -f resources.yaml
```

3. You will receive this error:
```
Error: GAL1113E: Failure reported by the Galasa Ecosystem. The Ecosystem believes there is a problem with this client program or the user input. Errors returned: 'GAL5024E: Error occurred because the Galasa Property is invalid. 'The 'value' field cannot be empty. The field 'value' is mandatory for the type GalasaProperty.''
```

4. Note that in Galasactl version 0.40.0 you can apply empty CPS properties:

```
galasactl properties set --namespace demo --name empty.prop.demo --value ""  
```

```
galasactl properties get --namespace demo --name empty.prop.demo           
namespace name           value
demo      empty.prop.demo 

Total:1
```

```
galasactl properties get --namespace demo --name mike.prop.demo --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
    namespace: demo
    name: empty.prop.demo
data:
    value: ""
```

## Expected behavior
The behaviour of resources apply and proeprties set should be consistent, and should match the allowed actions in etcd.
