### ISSUE TITLE
Many test pods marked marked as "Hung" during test runs at version 0.42.0

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#2269]
## Describe the bug
In a version 0.42.0 ecosystem when running our full test workload (about 66 tests) about a third of them do not complete and are marked as "Hung" by the ecosystem.

## Steps to reproduce
1. Install a version 0.42.0 ecosystem
2. Run many tests (we have max_engines set to 20 and are running on 1 k8s node)
3. Observe output from Galasactl and see many tests ending with status hung

## Expected behavior
All tests should pass. 

## Additional context
I can see in the engine controller pod that tests have null heartbeat:

```
16/06/2025 13:02:33.804 INFO  d.g.f.RunImpl - RunImpl created: Run: name: U136 heartbeat: null type: CLI group: ...
```

## Tasks
- [x] Stop runs in the `allocated` state from being returned when getting active runs
- [x] Add a separate timeout for runs in the `allocated` state, defaulting to 30mins
- [x] Make the allocated run timeout configurable as a value in the Helm chart

**Comment by Mark-J-Lawrence** [comment]
To add my thruppence to this, and to add context from our slack channels to this ticket, I believe the reason this is happening  is because the test pods weren't scheduling (due to the engine resource limits we has set up...then):

```
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-16T15:39:07Z"
    message: '0/11 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane:
      }, 3 node(s) had untolerated taint {ejat-engines: }, 7 Insufficient cpu. preemption:
      0/11 nodes are available: 4 Preemption is not helpful for scheduling, 7 No preemption
      victims found for incoming pod.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

It took some sniffing around in k8s to know this is the reason. It might be up for debate what should be done in this scenario (...or not perhaps!)....should the tests mark as `Hung` after a few minutes if what's really happening is k8s continually retrying to schedule the pod? It's not really Hung, it could be argued that this is a queued state still. Eventually, these pods may have scheduled?
Could Galasa be more aware that its k8s handling the resource limitations, perhaps not start the 'Hung' timer for it? Perhaps there could be a new test state for this?
